In [465]:
import pandas as pd

In [466]:
data=pd.read_csv("car_data.csv")

In [467]:
data.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [468]:
data.shape

(892, 6)

In [469]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [470]:
data.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [471]:
data.duplicated().sum()

np.int64(94)

In [472]:
data.drop_duplicates(inplace=True)

In [473]:
data.shape

(798, 6)

In [474]:
data.name.unique()

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Maruti Suzuki Alto 800 Vxi',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maruti Suzuki Baleno Delta 1.2',
       'Renault Duster 110 PS RxZ Diesel Plus',
       'Renault Duster 85 PS RxE Diesel', 'Honda City 1.5 S MT',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5 SX i DTEC',
       'Honda City', 'Datsun Redi GO S', 'Maruti Suzuki SX4 ZXI MT',
       'Mitsubishi Pajero Sport Limited Edition',
       'Maruti Suzuki Swift VXi 1.2 ABS BS IV', 'Honda City ZX CVT',
       'Maruti Suzuki Wagon R LX BS IV', 'Tata Indigo eCS LS CR4 BS IV',
       'Volkswagen Polo Highline Exquisite P',
       'I want to sell my car Tata Zest', 'Chevrolet Spark LS 1.0',
       'Renault Duster 110PS Diesel RxZ', 'Mini Cooper S 1.6',
       'Skoda Fabia 1.2L Diesel Ambiente', 'Renault Duster',
       'Mahindra Scorpio S4', 'Mahindra Scorpio VLX 2WD BS IV',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline Plus 1.5 Diesel AT',
       'Hyundai i20 Magna', 'Toyota Corolla Altis Diesel D4DG',
       'Hyundai Verna Transform SX VTVT',
       'Toyota Corolla Altis Petrol Ltd', 'Honda City 1.5 EXi New',
       'Skoda Fabia 1.2L Diesel Elegance', 'BMW 3 Series 320i',
       'Maruti Suzuki A Star Lxi', 'Toyota Etios GD',
       'Ford Figo Diesel EXI Option',
       'Maruti Suzuki Swift Dzire VXi 1.2 BS IV',
       'Chevrolet Beat LT Diesel', 'BMW 7 Series 740Li Sedan',
       'Mahindra XUV500 W8 AWD 2013', 'Hyundai i10 Magna 1.2',
       'Hyundai Verna Fluidic New', 'Maruti Suzuki Swift VXi 1.2 BS IV',
       'Maruti Suzuki Ertiga ZXI Plus', 'Maruti Suzuki Ertiga Vxi',
       'Maruti Suzuki Ertiga VDi', 'Maruti Suzuki Alto LXi BS III',
       'Hyundai Grand i10 Asta 1.1 CRDi', 'Honda Amaze 1.2 S i VTEC',
       'Hyundai i20 Asta 1.4 CRDI 6 Speed', 'Ford Figo Diesel EXI',
       'Maruti Suzuki Eeco 5 STR WITH AC HTR', 'Maruti Suzuki Ertiga ZXi',
       'Maruti Suzuki Esteem LXi BS III', 'Maruti Suzuki Ritz VXI',
       'Maruti Suzuki Ritz LDi', 'Maruti Suzuki Dzire VDI',
       'Toyota Etios Liva G', 'Hyundai i20 Sportz 1.4 CRDI',
       'Chevrolet Spark', 'Nissan Micra XV', 'Maruti Suzuki Swift',
       'Honda Amaze 1.5 S i DTEC', 'Chevrolet Beat', 'Toyota Corolla',
       'Honda City 1.5 V MT', 'Ford EcoSport Trend 1.5L TDCi',
       'Hyundai i20 Asta 1.2', 'Tata Indica V2 eLS',
       'Maruti Suzuki Alto 800 Lxi', 'Hindustan Motors Ambassador',
       'Toyota Corolla Altis 1.8 GL', 'Toyota Corolla Altis 1.8 J',
       'Toyota Innova 2.5 GX BS IV 7 STR',
       'Volkswagen Jetta Highline TDI AT',
       'Volkswagen Polo Comfortline 1.2L P', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Hyundai Elite i20',
       'Renault Kwid', 'Mahindra Scorpio VLX Airbag',
       'Chevrolet Spark LT 1.0', 'Datsun Redi GO T O',
       'Maruti Suzuki Swift RS VDI', 'Fiat Punto Emotion 1.2',
       'Hyundai i10 Sportz 1.2', 'Chevrolet Beat LT Opt Diesel',
       'Chevrolet Beat LS Diesel', 'Tata Indigo CS',
       'Maruti Suzuki Swift VDi', 'Hyundai Eon Era Plus',
       'Mahindra XUV500', 'Ford Fiesta', 'Maruti Suzuki Wagon R',
       'Hyundai i20', 'Tata Indigo eCS LX TDI BS III',
       'Hyundai Fluidic Verna 1.6 CRDi SX',
       'Commercial , DZire LDI, 2016, for sale', 'Fiat Petra ELX 1.2 PS',
       'Hyundai Santro Xing XS', 'Maruti Suzuki Ciaz VXi Plus',
       'Maruti Suzuki Zen VX', 'Hyundai Creta 1.6 SX Plus Petrol',
       'Tata indigo ecs LX, 201', 'Mahindra Scorpio SLX',
       'Toyota Innova 2.5 G BS III 8 STR',
       'Maruti Suzuki Wagon R LXI BS IV', 'Tata Nano Cx BSIV',
       'Maruti Suzuki Alto Std BS IV', 'Maruti Suzuki Wagon R LXi BS III',
       'Maruti Suzuki Swift VXI BSIII',
       'Tata Sumo Victa EX 10 by 7 Str BSIII', 'MARUTI SUZUKI DESI',
       'Volkswagen Passat Diesel Comfortline AT',
       'Renault Scala RxL Diesel Travelogue',
       'Hyundai Grand i10 Sportz O 1.2 Kappa VTVT',
       'Hyundai i20 Active 1.2 SX', 'Mahindra Xylo E4',
       'Mahindra Jeep MM 550 XDB', 'Mahindra Bolero SLE BS IV',
       'Force Motors Force One LX ABS 7 STR', 'Maruti Suzuki SX4',
       'Toyota Etios', 'Honda City ZX VTEC',
       'Maruti Suzuki Wagon R LX BS III', 'Honda City VX O MT Diesel',
       'Mahindra Thar CRDe 4x4 AC',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Mercedes Benz GLA Class 200 CDI Sport',
       'Land Rover Freelander 2 SE', 'Renault Kwid RXT',
       'Tata Aria Pleasure 4X2', 'Mercedes Benz B Class B180 Sports',
       'Datsun GO T O', 'Honda Jazz VX MT',
       'Hyundai i20 Active 1.4L SX O', 'Mini Cooper S',
       'Maruti Suzuki Ciaz ZXI Plus', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold Select Variant',
       'Maruti Suzuki Wagon R 1.0', 'Maruti Suzuki Esteem VXi BS III',
       'Chevrolet Enjoy 1.4 LS 8 STR', 'Maruti Suzuki Wagon R 1.0 VXi',
       'Nissan Terrano XL D Plus', 'Renault Duster 85 PS RxL Diesel',
       'Maruti Suzuki Dzire ZXI', 'Renault Kwid RXT Opt',
       'Maruti Suzuki Maruti 800 Std', 'Renault Kwid 1.0 RXT AMT',
       'Renault Scala RxL Diesel',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT O',
       'Chevrolet Beat LS Petrol', 'Hyundai Accent GLX', 'Yama',
       'Maruti Suzuki Swift LDi', 'Mahindra TUV300 T4 Plus',
       'Tata Indica V2 Xeta e GLE', 'Tata Indigo CS LS DiCOR',
       'Mahindra Scorpio VLX Special Edition BS III',
       'Tata Indica eV2 LS', 'Honda Accord',
       'Ford EcoSport Titanium 1.5 TDCi', 'Maruti Suzuki Ertiga',
       'Mahindra Scorpio 2.6 CRDe', 'Honda Mobilio',
       'Toyota Corolla Altis', 'Skoda Laura', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Vitara Brezza', 'Tata Manza Aura Quadrajet',
       'Chevrolet Sail UVA Petrol LT ABS',
       'Hyundai Verna Fluidic 1.6 VTVT SX',
       'Audi A4 2.0 TDI 177bhp Premium', 'Hyundai Elantra SX',
       'Mahindra Scorpio VLX 4WD Airbag', 'Mahindra KUV100 K8 D 6 STR',
       'Hyundai Grand i10', 'Hyundai i10', 'Hyundai i20 Active',
       'Datsun Redi GO', 'Toyota Etios Liva', 'Hyundai Accent',
       'Hyundai Verna', 'Toyota Fortuner', 'Hyundai i10 Sportz',
       'Mahindra Bolero Power Plus SLE', 'selling car Ta',
       'Honda City 1.5 V MT Exclusive', 'Chevrolet Spark LT 1.0 Airbag',
       'Tata Indigo eCS VX CR4 BS IV', 'Tata Zest 90',
       'Skoda Rapid Elegance 1.6 TDI CR MT', 'Tata Vista Quadrajet VX',
       'Maruti Suzuki Alto K10 VXi AT', 'Maruti Suzuki Zen LXi BS III',
       'Maruti Suzuki Swift Dzire Tour LDi', 'Honda City ZX EXi',
       'Chevrolet Beat Diesel', 'Maruti Suzuki Swift Dzire car',
       'Hyundai Verna 1.4 VTVT', 'Toyota Innova 2.5 E MS 7 STR BS IV',
       'Maruti Suzuki Maruti 800 Std – Befo',
       'Hyundai Elite i20 Asta 1.4 CRDI',
       'Maruti Suzuki Swift Dzire Tour (Gat',
       'Maruti Suzuki Versa DX2 8 SEATER BSIII',
       'Tata Indigo LX TDI BS III',
       'Volkswagen Vento Konekt Diesel Highline',
       'Mercedes Benz C Class 200 CDI Classic', 'URJE',
       'Hyundai Santro Xing GLS', 'Maruti Suzuki Omni Limited Edition',
       'Hyundai Sonata Transform 2.4 GDi MT',
       'Hyundai Elite i20 Sportz 1.2', 'Honda Jazz S MT',
       'Hyundai Grand i10 Sportz 1.2 Kappa VTVT',
       'Maruti Suzuki Zen LXi BSII',
       'Mahindra Scorpio W Turbo 2.6DX 9 Seater',
       'Swift Dzire Tour 27 Dec 2016 Regis', 'Maruti Suzuki Alto K10 VXi',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT', 'Mahindra XUV500 W8',
       'Hyundai i20 Magna O 1.2', 'Renault Duster 85 PS RxL Explore LE',
       'Honda Brio V MT', 'Mahindra TUV300 T8',
       'Nissan X Trail Select Variant', 'Ford Ikon 1.3 CLXi NXt Finesse',
       'Toyota Fortuner 3.0 4x4 MT', 'Tata Manza ELAN Quadrajet',
       'Tata zest x', 'Mahindra xyl',
       'Mercedes Benz A Class A 180 Sport Petrol', 'Tata Indigo LS',
       'Hyundai i20 Magna 1.2', 'Used Commercial Maruti Omn',
       'Honda Amaze 1.5 E i DTEC', 'Hyundai Verna 1.6 EX VTVT',
       'BMW 5 Series 520d Sedan', 'Skoda Superb 1.8 TFSI AT',
       'Audi Q3 2.0 TDI quattro Premium', 'Mahindra Bolero DI BSII',
       'Maruti Suzuki Zen Estilo LXI Green CNG',
       'Ford Figo Duratorq Diesel Titanium 1.4',
       'Maruti Suzuki Wagon R VXI BS IV', 'Mahindra Logan Diesel 1.5 DLS',
       'Tata Nano GenX XMA', 'Honda City SV', 'Ford Figo Petrol LXI',
       'Hyundai i10 Magna 1.2 Kappa2', 'Toyota Corolla H2',
       'Maruti Suzuki Swift Dzire Tour VXi', 'Tata Indigo CS eLS BS IV',
       'Hyundai Xcent Base 1.1 CRDi', 'Hyundai Accent Executive Edition',
       'Tata Zest XE 75 PS Diesel', 'Maruti Suzuki Dzire LDI',
       'Tata Sumo Gold LX BS IV', 'Toyota Corolla Altis GL Petrol',
       'Maruti Suzuki Eeco 7 STR', 'Toyota Fortuner 3.0 4x2 MT',
       'Mahindra XUV500 W6', 'Tata Tigor Revotron XZ',
       'Maruti Suzuki 800', 'Honda Mobilio S i DTEC',
       'Hyundai Verna 1.6 CRDI E', 'Maruti Suzuki Omni Select Variant',
       'Tata Indica', 'Hyundai Santro Xing', 'Maruti Suzuki Zen Estilo',
       'Honda Brio VX AT', 'Maruti Suzuki Wagon R Select Variant',
       'Tata Nano Lx BSIV', 'Jaguar XE XE Portfolio',
       'Hyundai Xcent S 1.2', 'Hyundai Eon Magna Plus',
       'Maruti Suzuki Ritz GENUS VXI',
       'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT',
       'Hyundai Eon D Lite Plus', 'Honda Amaze 1.2 VX i VTEC',
       'Maruti Suzuki Estilo VXi ABS BS IV',
       'Maruti Suzuki Vitara Brezza LDi O', 'Toyota Innova 2.0 V',
       'Hyundai Creta 1.6 SX Plus Petrol AT', 'Mahindra Scorpio Vlx BSIV',
       'Mitsubishi Lancer 1.8 LXi', 'Maruti Suzuki Maruti 800 AC',
       'Maruti Suzuki Alto 800 LXI CNG O', 'Ford Fiesta SXi 1.6 ABS',
       'Maruti Suzuki Ritz VDi', 'Maruti Suzuki Estilo LX BS IV',
       'Audi A6 2.0 TDI Premium', 'Maruti Suzuki Alto',
       'Maruti Suzuki Baleno Sigma 1.2', 'Hyundai Verna 1.6 SX VTVT AT',
       'Maruti Suzuki Swift GLAM', 'Hyundai Getz Prime 1.3 GVS',
       'Hyundai Santro', 'Hyundai Getz Prime 1.3 GLX',
       'Chevrolet Beat PS Diesel', 'Ford EcoSport Trend 1.5 Ti VCT',
       'Tata Indica V2 DLG', 'BMW X1 xDrive20d xLine',
       'Honda City 1.5 V AT', 'Tata Nano', 'Chevrolet Cruze LTZ AT',
       'Hyun', 'Maruti Suzuki Swift Dzire VDi', 'Mahindra XUV500 W10',
       'Maruti Suzuki Alto K10 LXi CNG', 'Hyundai Accent GLE',
       'Force Motors One SUV', 'Datsun Go Plus T O',
       'Chevrolet Spark 1.0 LT', 'Toyota Etios Liva GD',
       'Renault Duster 85PS Diesel RxL Optional with Nav',
       'Chevrolet Enjoy', 'BMW 5 Series 530i', 'Chevrolet Cruze LTZ',
       'Jeep Wrangler Unlimited 4x4 Diesel',
       'Hyundai Verna VGT CRDi SX ABS', 'Maruti Suzuki Omni',
       'Maruti Suzuki Celerio VDi', 'Tata Zest Quadrajet 1.3',
       'Tata Indigo CS eLX BS IV', 'Hyundai i10 Era',
       'Tata Indigo eCS LX CR4 BS IV', 'Tata Indigo Marina LS',
       'Commercial Chevrolet Sail Hatchback ca', 'Hyundai Xcent SX 1.2',
       'Tata Nano LX Special Edition', 'Commercial Car Ta',
       'Renault Duster 110 PS RxZ Diesel',
       'Maruti Suzuki Wagon R AX BSIV', 'Maruti Suzuki Alto K10 New',
       'tata Indica', 'Mahindra Xylo E8', 'Tata Manza Aqua Quadrajet',
       'Used bt new conditions ta', 'Renault Kwid 1.0', 'Sale tata',
       'Tata Venture EX 8 STR', 'Maruti Suzuki Swift Dzire Tour LXi',
       'Maruti Suzuki Alto LX BSII', 'Skoda Octavia Classic 1.9 TDI MT',
       'Maruti Suzuki Omni LPG BS IV', 'Tata Sumo Gold EX BS IV',
       'Tata indigo 2017 top model..', 'Hyundai Verna 1.6 CRDI SX',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str', 'Ford Ikon 1.6 Nxt',
       'Tata indigo', 'Toyota Innova 2.5 V 7 STR', 'Nissan Sunny XL',
       'Maruti Suzuki Swift VDi BS IV',
       'very good condition tata bolts are av', 'Toyota Innova 2.0 G4',
       'Sale Hyundai xcent commerc', 'Maruti Suzuki Swift VDi ABS',
       'Hyundai Elite i20 Asta 1.2', 'Volkswagen Polo Trendline 1.5L D',
       'Toyota Etios Liva Diesel', 'Maruti Suzuki Ciaz ZXi Plus RS',
       'Hyundai Elantra 1.8 S', 'Ford EcoSport Trend 1.5L Ti VCT',
       'Jaguar XF 2.2 Diesel Luxury',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'BMW 3 Series 320d Sedan',
       'Maruti Suzuki Swift ZXi 1.2 BS IV', 'BMW X1 sDrive20d',
       'Maruti Suzuki S Cross Sigma 1.3', 'Maruti Suzuki Ertiga LDi',
       'Volkswagen Vento Comfortline Petrol', 'Mahindra KUV100',
       'Maruti Suzuki Swift Dzire Tour VDi', 'Mahindra Scorpio 2.6 SLX',
       'Maruti Suzuki Omni 8 STR BS III',
       'Volkswagen Jetta Comfortline 1.9 TDI AT', 'Volvo S80 Summum D4',
       'Toyota Corolla Altis VL AT Petrol',
       'Mitsubishi Pajero Sport 2.5 AT', 'Chevrolet Beat LT Petrol',
       'BMW X1', 'Mercedes Benz C Class C 220 CDI Avantgarde',
       'Volkswagen Vento Comfortline Diesel', 'Tata Indigo CS GLS',
       'Ford Figo Petrol Titanium', 'Honda City ZX GXi',
       'Maruti Suzuki Wagon R Duo Lxi', 'Maruti Suzuki Zen LX BSII',
       'Renault Duster RxL Petrol', 'Maruti Suzuki Baleno Zeta 1.2',
       'Honda WR V S MT Petrol', 'Renault Duster 110 PS RxL Diesel',
       'Mahindra Scorpio LX BS III',
       'Maruti Suzuki SX4 Celebration Diesel',
       'Audi A3 Cabriolet 40 TFSI',
       'I want to sell my commercial car due t',
       'Hyundai Santro AE GLS Audio',
       'i want sale my car.no emi....uber atta', 'Tata ZEST 6 month old',
       'Mahindra Xylo D2 BS IV', 'Hyundai Getz GLE',
       'Hyundai Creta 1.6 SX', 'Hyundai Santro Xing XL AT eRLX Euro III',
       'Hyundai Santro Xing XL eRLX Euro III',
       'Tata Indica V2 DLS BS III', 'Honda City 1.5 E MT',
       'Nissan Micra XL', 'Honda City 1.5 S Inspire',
       'Tata Indica eV2 eXeta eGLX', 'Maruti Suzuki Omni E 8 STR BS IV',
       'MARUTI SUZUKI ERTIGA F', 'Hyundai Verna 1.6 CRDI SX Plus AT',
       'Chevrolet Tavera LS B3 10 Seats BSII', 'Tata Tiago Revotron XM',
       'Tata Tiago Revotorq XZ', 'Tata Nexon', 'Tata',
       'Hindustan Motors Ambassador Classic Mark 4 – Befo',
       'Ford Fusion 1.4 TDCi Diesel',
       'Fiat Linea Emotion 1.4 L T Jet Petrol',
       'Ford Ikon 1.3 Flair Josh 100', 'Tata Indica V2 LS',
       'Mahindra Xylo D2', 'Hyundai Eon Magna',
       'Tata Sumo Grande MKII GX', 'Volkswagen Polo Highline1.2L P',
       'Tata Tiago Revotron XZ', 'Tata Indigo eCS',
       '2012 Tata Sumo Gold f', 'Mahindra Xylo E8 BS IV',
       'Well mentained Tata Sumo',
       'all paper updated tata indica v2 and u',
       'Maruti Ertiga showroom condition with',
       '7 SEATER MAHINDRA BOLERO IN VERY GOOD', '9 SEATER MAHINDRA BOL',
       'scratch less Tata I', 'Maruti Suzuki swift dzire for sale in',
       'Commercial Chevrolet beat for sale in',
       'urgent sell my Mahindra qu', 'Tata Sumo Gold FX BSIII',
       'sell my car Maruti Suzuki Swif',
       'Maruti Suzuki Swift Dzire good car fo', 'Hyunda',
       'Commercial Maruti Suzuki Alto Lxi 800', 'urgent sale Ta',
       'Maruti Suzuki Alto vxi t', 'tata', 'TATA INDI', 'Hyundai Creta',
       'Tata Bolt XM Petrol', 'Hyundai Venue', 'Maruti Suzuki Ritz',
       'Renault Lodgy', 'Hyundai i20 Asta',
       'Maruti Suzuki Swift Select Variant', 'Tata Indica V2 DLX BS III',
       'Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV',
       'Toyota Innova 2.5 E 8 STR', 'Mahindra KUV100 K8 6 STR',
       'Datsun Go Plus', 'Ford Endeavor 4x4 Thunder Plus',
       'Tata Indica V2', 'Hyundai Santro Xing GL',
       'Toyota Innova 2.5 Z Diesel 7 Seater',
       'Any type car avaiabel hare...comercica', 'Maruti Suzuki Alto AX',
       'Mahindra Logan', 'Maruti Suzuki 800 Std BS III',
       'Chevrolet Sail 1.2 LS',
       'Volkswagen Vento Highline Plus 1.5 Diesel', 'Tata Manza',
       'Toyota Innova 2.0 G1 Petrol 8seater', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Maruti Suzuki Swift Dzire',
       'Hyundai i20 Select Variant', 'Honda City VX Petrol',
       'Hyundai Getz', 'Mercedes Benz C Class 200 K MT', 'Skoda Fabia',
       'Maruti Suzuki Alto 800 Select Variant',
       'Maruti Suzuki Ritz VXI ABS', 'tata zest 2017 f',
       'Tata Indica V2 DLE BS III', 'Ta', 'Tata Zest XM Diesel',
       'Honda Amaze 1.2 E i VTEC', 'Chevrolet Sail 1.2 LT ABS'],
      dtype=object)

In [475]:
data.name=data.name.str.split().str[0:3].str.join(" ")

In [476]:
data

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2,Chevrolet,2014,"1,60,000",Petrol,NaN

In [477]:
data.year.unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [478]:
"150k".isnumeric()

False

In [479]:
data1 = data[(data.year.str.isnumeric())] #we can also reassign the data variable there but we can create a new variale there

       ######### FOR UPDATING THE EXISTING data FILE  for particular key/column ,############

In [480]:
#data.year=data["year"][data.year.str.isnumeric()]  #But nan comes instead of not numeric data

In [481]:
#data.year.isna().sum()

In [482]:
#data.info()

In [483]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 749 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        749 non-null    object
 1   company     749 non-null    object
 2   year        749 non-null    object
 3   Price       749 non-null    object
 4   kms_driven  748 non-null    object
 5   fuel_type   745 non-null    object
dtypes: object(6)
memory usage: 41.0+ KB

In [484]:
data1.year=data1.year.astype(int)

C:\Users\hp\AppData\Local\Temp\ipykernel_2136\2964951714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1.year=data1.year.astype(int)

Pandas doesn't know whether data1 is

. a completely new DataFrame ✅
. or just a view of data ⚠️

When you write:
data1.year = data1.year.astype(int)
Pandas says:

"Wait! If data1 is only a view of data, should I modify data too? I'm not sure."

So it shows the warning.
To fixing it we can use the .copy() function

In [485]:
data1 = data[(data.year.str.isnumeric())].copy()  #.copy() means it is a copy ,not the original data can be changing

In [486]:
data1.year=data1.year.astype(int)

In [487]:
data.Price.unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [488]:
ask_for_price=data1[data1.Price=="Ask For Price"]

In [489]:
data1=data1[data1.Price!="Ask For Price"]

              OR

In [490]:
data1=data1[~(data1.Price=="Ask For Price")]  # ~ means not

In [491]:
data1.Price=data1.Price.str.replace(',','').astype(int)

In [492]:
data1

                       name    company  year   Price    kms_driven fuel_type
0       Hyundai Santro Xing    Hyundai  2007   80000    45,000 kms    Petrol
1       Mahindra Jeep CL550   Mahindra  2006  425000        40 kms    Diesel
3         Hyundai Grand i10    Hyundai  2014  325000    28,000 kms    Petrol
4    Ford EcoSport Titanium       Ford  2014  575000    36,000 kms    Diesel
6                 Ford Figo       Ford  2012  175000    41,000 kms    Diesel
..                      ...        ...   ...     ...           ...       ...
886    Toyota Corolla Altis     Toyota  2009  300000  1,32,000 kms    Petrol
888            Tata Zest XM       Tata  2018  260000    27,000 kms    Diesel
889      Mahindra Quanto C8   Mahindra  2013  390000    40,000 kms    Diesel
890         Honda Amaze 1.2      Honda  2014  180000        Petrol       NaN
891      Chevrolet Sail 1.2  Chevrolet  2014  160000        Petrol       NaN

[727 rows x 6 columns]

In [493]:
data1=data1[data1.kms_driven!="Petrol"].copy()

In [494]:
data1

                       name   company  year   Price    kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000    45,000 kms    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000        40 kms    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000    28,000 kms    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000    36,000 kms    Diesel
6                 Ford Figo      Ford  2012  175000    41,000 kms    Diesel
..                      ...       ...   ...     ...           ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000    50,000 kms    Petrol
885          Tata Indica V2      Tata  2009  110000    30,000 kms    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000  1,32,000 kms    Petrol
888            Tata Zest XM      Tata  2018  260000    27,000 kms    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000    40,000 kms    Diesel

[725 rows x 6 columns]

In [495]:
data1.kms_driven=data1.kms_driven.str.replace(",","").str.replace("kms","").astype(int)

In [496]:
#                              OR

In [497]:
#data1.kms_driven=data1.kms_driven.str.replace(",","").str.split().str[0].astype(int)

In [498]:
data1

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[725 rows x 6 columns]

In [499]:
data1.fuel_type.unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [500]:
data1[data1.fuel_type.isna()]

               name company  year   Price  kms_driven fuel_type
132  Toyota Corolla  Toyota  2009  275000       26000       NaN

In [501]:
data1.isna().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     1
dtype: int64

In [502]:
data1.fuel_type=data1.fuel_type.fillna(data1.fuel_type.mode()[0])

In [503]:
data1.fuel_type.isna().sum()

np.int64(0)

In [504]:
data1.fuel_type.unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [505]:
data1

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[725 rows x 6 columns]

In [506]:
ask_for_price["Price"]=ask_for_price.Price.replace("Ask For Price",data1.Price.median())  #when we do inplace=True,So the future warning comes ,for we can assign the values

C:\Users\hp\AppData\Local\Temp\ipykernel_2136\1282993090.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ask_for_price["Price"]=ask_for_price.Price.replace("Ask For Price",data1.Price.median())  #when we do inplace=True,So the future warning comes ,for we can assign the values

In [ ]:
 ################ IN THE UPPER CODE IT SHOWS WARNNG BECAUSE IN FUTURE VERSIONS WHEN WE CANNOT TYPECAST OUR NUMBERS DATA INTO FLOAT SO IT CAN DO IT AUTOMATICALLY ,FOR SAFE ZONE WE CAN TYPECAST WITH OUR OWN ###############

In [514]:
ask_for_price["Price"]=ask_for_price.Price.astype(float)

In [515]:
ask_for_price

,name,company,year,Price,kms_driven,fuel_type
2,Maruti Suzuki Alto,Maruti,2018,290000.0,"22,000 kms",Petrol
5,Ford EcoSport Titanium,Ford,2015,290000.0,"59,000 kms",Diesel
69,I want to,I,2017,290000.0,NaN,NaN
138,Maruti Suzuki Alto,Maruti,2018,290000.0,"28,028 kms",Petrol
295,Maruti Suzuki Swift,Maruti,2010,290000.0,"52,000 kms",Diesel
304,Tata Indica eV2,Tata,2017,290000.0,"84,000 kms",Diesel
388,Maruti Suzuki Alto,Maruti,2018,290000.0,"24,000 kms",Petrol
449,Maruti Suzuki Zen,Maruti,2011,290000.0,"16,000 kms",Petrol
503,Hyundai Xcent Base,Hyundai,2015,290000.0,"1,80,000 kms",Diesel
511,Hyundai Xcent S,Hyundai,2015,290000.0,"35,000 kms",Petrol
524,Toyota Innova 2.0,Toyota,2009,290000.0,"15,574 kms",Diesel
567,Datsun Go Plus,Datsun,2016,290000.0,5 kms,Petrol
613,Mahindra KUV100 K8,Mahindra,2018,290000.0,"7,500 kms",Diesel
619,Maruti Suzuki Alto,Maruti,2002,290000.0,"56,000 kms",Petrol
634,Hyundai Elite i20,Hyundai,2015,290000.0,"49,500 kms",Petrol
763,Tata Nexon,Tata,2019,290000.0,0 kms,Petrol
822,Hyundai Venue,Hyundai,2019,290000.0,"7,000 kms",Diesel
826,Renault Lodgy,Renault,2016,290000.0,"20,000 kms",Diesel
848,Maruti Suzuki Alto,Maruti,2019,290000.0,"1,500 kms",Petrol
854,Volkswagen Vento Highline,Volkswagen,2015,290000.0,"38,900 kms",Diesel
859,Toyota Innova 2.0,Toyota,2019,290000.0,"4,000 kms",Petrol
882,Maruti Suzuki Alto,Maruti,2015,290000.0,"70,000 kms",Petrol

In [508]:
data2=pd.concat([data1,ask_for_price]).sample(747)

In [509]:
data2   # When we see in the data ,So there is the median of price,Replace from ask for price i.e(290000) is pepeating continously,For handling this we can write .sample(747) for aranging them randomly

                       name     company  year      Price kms_driven fuel_type
661       Hyundai Grand i10     Hyundai  2016   380000.0      27000    Petrol
8    Ford EcoSport Ambiente        Ford  2016   830000.0      24530    Diesel
350             Hyundai i10     Hyundai  2012   244999.0      38000    Petrol
769         Ford Fusion 1.4        Ford  2007   125000.0      85455    Diesel
460    Maruti Suzuki Baleno      Maruti  2016   500000.0      28000    Petrol
..                      ...         ...   ...        ...        ...       ...
817         Volkswagen Polo  Volkswagen  2013   299999.0      48000    Diesel
158          Datsun Redi GO      Datsun  2016   245000.0       7000    Petrol
427          Nissan X Trail      Nissan  2019  1200000.0        300    Diesel
647       Hyundai Elite i20     Hyundai  2015   500000.0      22000    Petrol
88     Toyota Corolla Altis      Toyota  2010   351000.0      38000    Diesel

[747 rows x 6 columns]

In [510]:
data2.reset_index(drop=True,inplace=True)

In [511]:
data2

                       name     company  year      Price kms_driven fuel_type
0         Hyundai Grand i10     Hyundai  2016   380000.0      27000    Petrol
1    Ford EcoSport Ambiente        Ford  2016   830000.0      24530    Diesel
2               Hyundai i10     Hyundai  2012   244999.0      38000    Petrol
3           Ford Fusion 1.4        Ford  2007   125000.0      85455    Diesel
4      Maruti Suzuki Baleno      Maruti  2016   500000.0      28000    Petrol
..                      ...         ...   ...        ...        ...       ...
742         Volkswagen Polo  Volkswagen  2013   299999.0      48000    Diesel
743          Datsun Redi GO      Datsun  2016   245000.0       7000    Petrol
744          Nissan X Trail      Nissan  2019  1200000.0        300    Diesel
745       Hyundai Elite i20     Hyundai  2015   500000.0      22000    Petrol
746    Toyota Corolla Altis      Toyota  2010   351000.0      38000    Diesel

[747 rows x 6 columns]

In [512]:
data2[data2.company=="Maruti"]["Price"].mean()

np.float64(271795.2047619048)

In [463]:
data2[(data2.company=="Maruti") & (data2.fuel_type=="Petrol")]["Price"].mean()

np.float64(223353.8)

## Descretization And Binning

In [13]:
data1=pd.read_excel("Bengaluru_House_Data.xlsx")

In [14]:
data1

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,2026-12-19 00:00:00,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,2026-06-18 00:00:00,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [15]:
data1.shape

(13320, 9)

In [16]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [18]:
data1.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,2026-12-19 00:00:00,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [20]:
data1.sample(10)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
5264,Super built-up Area,Ready To Move,Kodichikkanahalli,3 BHK,DiamiSa,1560,2.0,2.0,65.0
1846,Built-up Area,Ready To Move,NRI Layout,2 Bedroom,NaN,1300,2.0,0.0,120.0
9879,Built-up Area,Ready To Move,Vishwapriya Layout,5 Bedroom,NaN,2800,5.0,3.0,130.0
12854,Built-up Area,Ready To Move,Tumkur Road,4 Bedroom,NaN,1100,2.0,1.0,60.0
8970,Super built-up Area,Ready To Move,Raja Rajeshwari Nagar,3 BHK,NaonySy,1640,3.0,1.0,86.8
2261,Super built-up Area,Ready To Move,Dasarahalli,3 BHK,Sooneoo,1901,3.0,2.0,119.0
7366,Plot Area,Ready To Move,Gottigere,4 Bedroom,NaN,2500,3.0,2.0,120.0
6609,Built-up Area,Ready To Move,Hennur Gardens,3 BHK,PlhtsHe,1490,2.0,1.0,115.0
5867,Super built-up Area,Ready To Move,Sarjapur Road,2 BHK,Maager,1000,2.0,1.0,38.5
7119,Built-up Area,Ready To Move,EPIP Zone,3 BHK,NaN,1709,3.0,1.0,80.0

In [21]:
data1.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [22]:
emp = pd.DataFrame({'emp_name':['nasir','asad','fahan' ,'noman', 'ali', 'ahmer','ahmed', 'hasan', 'umer', 'jawed', 'fahad' , 'rehan', 'tahir'],
                'country':['pak', 'pak', 'ind', 'usa', 'iran', 'iraq', 'bangla', 'uae', 'uae', 'iraq','iran','usa','pak']})

In [23]:
country_capital = {'pak':'islambad', 'ind':'dehli','usa':'washington','iran':'tehran', 'iraq':'baghdad', 'uae':'abudhabi','bangla':'dhaka'}

In [25]:
emp["capital"]=emp.country.map(country_capital)

In [26]:
emp

   emp_name country     capital
0     nasir     pak    islambad
1      asad     pak    islambad
2     fahan     ind       dehli
3     noman     usa  washington
4       ali    iran      tehran
5     ahmer    iraq     baghdad
6     ahmed  bangla       dhaka
7     hasan     uae    abudhabi
8      umer     uae    abudhabi
9     jawed    iraq     baghdad
10    fahad    iran      tehran
11    rehan     usa  washington
12    tahir     pak    islambad