### Computing Indicator/Dummy variables
- Encoding

In [2]:
import pandas as pd

In [3]:
data=pd.read_excel("employee.xlsx")

In [6]:
data[["Emp_ID","Designation","Department","Salary"]]
data.Emp_ID

0     1101
1     1107
2     1203
3     1005
4     2123
5     2451
6     1111
7     1001
8     1234
9     2156
10    6543
11    3214
12    2156
13    1098
14    2912
15    1222
16    2156
17    2123
18    1005
19    2123
20    6543
21    3214
22    2156
23    1098
24    2156
25    2123
Name: Emp_ID, dtype: int64

Note:Everything system process is transformed into binary

In [7]:
data.Designation.unique()

array(['Manager', 'Officer', 'Office Boy', 'Accountant', 'Engineer'],
      dtype=object)

Data: is Quantitative and Qualitative  #    In the curent scenerio the data is designation
Quantitative:
           [12,34,56,78,89,76,45,76]
Qualitative:
          Nominal:["red",'orange','blue','green']
          Ordinal:["Poor",'Good','Very Good','Excellent']

In [15]:
data["Designation1"]=data.Designation.replace(['Manager', 'Officer', 'Office Boy', 'Accountant', 'Engineer'],[0,1,2,3,4])
data

C:\Users\hp\AppData\Local\Temp\ipykernel_9468\2999468.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Designation1"]=data.Designation.replace(['Manager', 'Officer', 'Office Boy', 'Accountant', 'Engineer'],[0,1,2,3,4])

    Serial  Emp_ID Designation  Department   Age    Salary  Designation1
0        1    1101     Manager    Accounts  50.0  200000.0             0
1        2    1107     Officer          IT  30.0   80000.0             1
2        3    1203     Officer          HR  28.0       NaN             1
3        4    1005     Manager          HR  45.0  120000.0             0
4        5    2123  Office Boy    Accounts  27.0   45000.0             2
5        6    2451  Accountant         NaN  34.0  100000.0             3
6        7    1111  Accountant    Accounts   NaN  110000.0             3
7        8    1001     Officer          IT  25.0   75000.0             1
8        9    1234     Manager          IT  23.0       NaN             0
9       10    2156    Engineer  Production  45.0   89000.0             4
10      11    6543     Officer  Production  29.0  100000.0             1
11      12    3214  Accountant     Account  49.0  123000.0             3
12      13    2156    Engineer  Production  45.0   89000.0             4
13      14    1098     Officer          IT  25.0  100000.0             1
14      15    2912     Officer          IT  31.0   90000.0             1
15      16    1222     Officer         NaN  25.0       NaN             1
16      17    2156    Engineer  Production  45.0   89000.0             4
17      18    2123  Office Boy    Accounts  27.0   45000.0             2
18      19    1005     Manager          HR  45.0  120000.0             0
19      20    2123  Office Boy    Accounts  27.0   45000.0             2
20      21    6543     Officer  Production  29.0  100000.0             1
21      22    3214  Accountant     Account  49.0  123000.0             3
22      23    2156    Engineer  Production  45.0   89000.0             4
23      24    1098     Officer          IT  25.0  100000.0             1
24      25    2156    Engineer  Production  45.0   89000.0             4
25      26    2123  Office Boy    Accounts  27.0   45000.0             2

## One Hot Encoding

In [18]:
pd.get_dummies(data.Designation,dtype=int)

    Accountant  Engineer  Manager  Office Boy  Officer
0            0         0        1           0        0
1            0         0        0           0        1
2            0         0        0           0        1
3            0         0        1           0        0
4            0         0        0           1        0
5            1         0        0           0        0
6            1         0        0           0        0
7            0         0        0           0        1
8            0         0        1           0        0
9            0         1        0           0        0
10           0         0        0           0        1
11           1         0        0           0        0
12           0         1        0           0        0
13           0         0        0           0        1
14           0         0        0           0        1
15           0         0        0           0        1
16           0         1        0           0        0
17           0         0        0           1        0
18           0         0        1           0        0
19           0         0        0           1        0
20           0         0        0           0        1
21           1         0        0           0        0
22           0         1        0           0        0
23           0         0        0           0        1
24           0         1        0           0        0
25           0         0        0           1        0

In [19]:
encoded=pd.get_dummies(data,dtype=int)

In [22]:
data.shape

(26, 7)

In [23]:
encoded.shape

(26, 15)

### Data Wrangling :Join,Combine,and Reshape

#### 8.2 Combining and Merging DataSets

In [29]:
d0=pd.read_excel("test_data.xlsx",sheet_name=0)
d1=pd.read_excel("test_data.xlsx",sheet_name=1)
d2=pd.read_excel("test_data.xlsx",sheet_name=2)

In [34]:
d01=pd.concat([d0,d1],axis=0)

In [35]:
d01.reset_index(drop=True,inplace=True)

In [ ]:
d01

In [40]:
d02=pd.concat([d0,d2],axis=1)

In [41]:
d02

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,sales_man_id,sales_man_name,Region,Sales,Amount
0,1,Asad,Karachi,123,Jawed,1,Asad,A,100,100000
1,2,Sumair,Lahore,123,Jawed,2,Sumair,B,300,450000
2,3,Farjad,Karachi,145,Najam,45,Ali,C,234,125000
3,4,Hassan,Lahore,567,Najam,34,Sana,D,231,652000
4,5,Nasir,Hyderabad,234,Jawed,5,Nasir,E,324,145000
5,6,Kashif,Hyderabad,234,Faisal,6,Kashif,F,123,825000
6,7,Sana,Lahore,567,Faisal,7,Sana,G,129,125000
7,8,Fatima,Karachi,345,Najam,8,Fatima,H,345,325600
8,9,Abdullah,Karachi,123,Faisal,99,Farhan,I,400,895200

In [44]:
pd.merge(d0,d2,on="sales_man_id").drop("sales_man_name_y",axis=1)

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,Region,Sales,Amount
0,1,Asad,Karachi,123,Jawed,A,100,100000
1,2,Sumair,Lahore,123,Jawed,B,300,450000
2,5,Nasir,Hyderabad,234,Jawed,E,324,145000
3,6,Kashif,Hyderabad,234,Faisal,F,123,825000
4,7,Sana,Lahore,567,Faisal,G,129,125000
5,8,Fatima,Karachi,345,Najam,H,345,325600

In [45]:
pd.merge(d0,d2,on="sales_man_name")     #The default merge type is inner

,sales_man_id_x,sales_man_name,sales_man_city,product_id,manager,sales_man_id_y,Region,Sales,Amount
0,1,Asad,Karachi,123,Jawed,1,A,100,100000
1,2,Sumair,Lahore,123,Jawed,2,B,300,450000
2,5,Nasir,Hyderabad,234,Jawed,5,E,324,145000
3,6,Kashif,Hyderabad,234,Faisal,6,F,123,825000
4,7,Sana,Lahore,567,Faisal,34,D,231,652000
5,7,Sana,Lahore,567,Faisal,7,G,129,125000
6,8,Fatima,Karachi,345,Najam,8,H,345,325600

## Outer

In [48]:
pd.merge(d0,d2,on="sales_man_id",how="outer")

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,sales_man_name_y,Region,Sales,Amount
0,1,Asad,Karachi,123.0,Jawed,Asad,A,100.0,100000.0
1,2,Sumair,Lahore,123.0,Jawed,Sumair,B,300.0,450000.0
2,3,Farjad,Karachi,145.0,Najam,NaN,NaN,NaN,NaN
3,4,Hassan,Lahore,567.0,Najam,NaN,NaN,NaN,NaN
4,5,Nasir,Hyderabad,234.0,Jawed,Nasir,E,324.0,145000.0
5,6,Kashif,Hyderabad,234.0,Faisal,Kashif,F,123.0,825000.0
6,7,Sana,Lahore,567.0,Faisal,Sana,G,129.0,125000.0
7,8,Fatima,Karachi,345.0,Najam,Fatima,H,345.0,325600.0
8,9,Abdullah,Karachi,123.0,Faisal,NaN,NaN,NaN,NaN
9,34,NaN,NaN,NaN,NaN,Sana,D,231.0,652000.0
10,45,NaN,NaN,NaN,NaN,Ali,C,234.0,125000.0
11,99,NaN,NaN,NaN,NaN,Farhan,I,400.0,895200.0

In [49]:
d0

   sales_man_id sales_man_name sales_man_city  product_id manager
0             1           Asad        Karachi         123   Jawed
1             2         Sumair         Lahore         123   Jawed
2             3         Farjad        Karachi         145   Najam
3             4         Hassan         Lahore         567   Najam
4             5          Nasir      Hyderabad         234   Jawed
5             6         Kashif      Hyderabad         234  Faisal
6             7           Sana         Lahore         567  Faisal
7             8         Fatima        Karachi         345   Najam
8             9       Abdullah        Karachi         123  Faisal

In [50]:
d1

    sales_man_id sales_man_name sales_man_city  product_id manager  Experience
0              1           Asad        Karachi         123   Jawed           2
1             22           Umer         Lahore         123   Jawed           3
2             33        Huzaifa        Karachi         145   Najam           4
3              4         Hassan         Lahore         567   Najam           5
4             55        Hussain      Hyderabad         234   Jawed           6
5             66            Ali      Hyderabad         234  Faisal           7
6             77          Sadaf         Lahore         567  Faisal           8
7             88          Kiran        Karachi         345   Najam           9
8             99            Ali        Karachi         123  Faisal           1
9            101           Asad      Hyderabad         432   Jawed           4
10           101           Asad      Hyderabad         432   Jawed           5

In [53]:
pd.merge(d0,d1,on="sales_man_id",how='left')

,sales_man_id,sales_man_name_x,sales_man_city_x,product_id_x,manager_x,sales_man_name_y,sales_man_city_y,product_id_y,manager_y,Experience
0,1,Asad,Karachi,123,Jawed,Asad,Karachi,123.0,Jawed,2.0
1,2,Sumair,Lahore,123,Jawed,NaN,NaN,NaN,NaN,NaN
2,3,Farjad,Karachi,145,Najam,NaN,NaN,NaN,NaN,NaN
3,4,Hassan,Lahore,567,Najam,Hassan,Lahore,567.0,Najam,5.0
4,5,Nasir,Hyderabad,234,Jawed,NaN,NaN,NaN,NaN,NaN
5,6,Kashif,Hyderabad,234,Faisal,NaN,NaN,NaN,NaN,NaN
6,7,Sana,Lahore,567,Faisal,NaN,NaN,NaN,NaN,NaN
7,8,Fatima,Karachi,345,Najam,NaN,NaN,NaN,NaN,NaN
8,9,Abdullah,Karachi,123,Faisal,NaN,NaN,NaN,NaN,NaN

In [54]:
pd.merge(d0,d1,on="sales_man_id",how="right")

,sales_man_id,sales_man_name_x,sales_man_city_x,product_id_x,manager_x,sales_man_name_y,sales_man_city_y,product_id_y,manager_y,Experience
0,1,Asad,Karachi,123.0,Jawed,Asad,Karachi,123,Jawed,2
1,22,NaN,NaN,NaN,NaN,Umer,Lahore,123,Jawed,3
2,33,NaN,NaN,NaN,NaN,Huzaifa,Karachi,145,Najam,4
3,4,Hassan,Lahore,567.0,Najam,Hassan,Lahore,567,Najam,5
4,55,NaN,NaN,NaN,NaN,Hussain,Hyderabad,234,Jawed,6
5,66,NaN,NaN,NaN,NaN,Ali,Hyderabad,234,Faisal,7
6,77,NaN,NaN,NaN,NaN,Sadaf,Lahore,567,Faisal,8
7,88,NaN,NaN,NaN,NaN,Kiran,Karachi,345,Najam,9
8,99,NaN,NaN,NaN,NaN,Ali,Karachi,123,Faisal,1
9,101,NaN,NaN,NaN,NaN,Asad,Hyderabad,432,Jawed,4
10,101,NaN,NaN,NaN,NaN,Asad,Hyderabad,432,Jawed,5