## Pandas
  - Python libraray for data analysis



 ### Pandas Data Structure
   - Pandas Series object(series)
   - Pandas Data Frame object(Data Frame)

### Pandas Series
      Data in one Dimension is series
      Data with only single column

In [1]:
#A series with default indices (integer indices)
import pandas as pd

### Class Work

In [3]:
s2=pd.Series(["apple","oranges","mangoes","cherries"])
s2

0       apple
1     oranges
2     mangoes
3    cherries
dtype: object

Components:
        values:We provided values
        Index:It uses default indices
        Dtype:Since all values are strings(Object)
        Name:Name of the series

In [25]:
s2=pd.Series(["Apple","Oranges","Mangoes","Cherries"],index=[12,34,54,76],name="Fruits")
s2

12       Apple
34     Oranges
54     Mangoes
76    Cherries
Name: Fruits, dtype: object

In [26]:
s2.name

'Fruits'

In [27]:
s3=pd.Series([27,23,54,46,77,30,65],index=["Apples","Mangoes","Kiwi","Banana","Cherries","Watermelon","Grapes"])

In [28]:
#Indices can be string indices

In [29]:
s3

Apples        27
Mangoes       23
Kiwi          54
Banana        46
Cherries      77
Watermelon    30
Grapes        65
dtype: int64

In [30]:
#Note : When providing string indices,Still we can refer to default intr indices

In [31]:
s3["Kiwi"]

np.int64(54)

In [32]:
s3["Mangoes"]

np.int64(23)

In [33]:
s2[34]

'Oranges'

In [35]:
# Using Default indices over string indices
s3

Apples        27
Mangoes       23
Kiwi          54
Banana        46
Cherries      77
Watermelon    30
Grapes        65
dtype: int64

In [37]:
s3.iloc[4]

np.int64(77)

In [38]:
s2.iloc[3]

'Cherries'

In [40]:
s3.loc["Grapes"]  #Correct way of writting this

np.int64(65)

## Slice a Series

In [41]:
s2

12       Apple
34     Oranges
54     Mangoes
76    Cherries
Name: Fruits, dtype: object

In [43]:
s2.iloc[0:3]   # Integer index don't includes last index in slice in iloc

12      Apple
34    Oranges
54    Mangoes
Name: Fruits, dtype: object

In [46]:
s2.loc[12:76]

12       Apple
34     Oranges
54     Mangoes
76    Cherries
Name: Fruits, dtype: object

In [45]:
#Where string index also include last one also
s3["Mangoes":"Grapes"]

Mangoes       23
Kiwi          54
Banana        46
Cherries      77
Watermelon    30
Grapes        65
dtype: int64

### Youtube Video Work

In [3]:
#s1=pd.Series([11,12,23,22,44,33,45,56,67])
s1=pd.Series([11,22,33,44,55,6,66,76,23.4])
s1

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
5     6.0
6    66.0
7    76.0
8    23.4
dtype: float64

In [4]:
s1.values

array([11. , 22. , 33. , 44. , 55. ,  6. , 66. , 76. , 23.4])

In [5]:
s1.index

RangeIndex(start=0, stop=9, step=1)

In [6]:
s1.dtype

dtype('float64')

In [7]:
s1.size

9

In [8]:
type(s1)

pandas.core.series.Series

In [9]:
len(s1)

9

In [10]:
# A series with costomized indices (labels)(label indices)
s2=pd.Series([11,12,23,22,44,33,45,56], index=["apples","oranges","bananas","mangoes","cheries","grapes","watermelons","peeches"])
s2

apples         11
oranges        12
bananas        23
mangoes        22
cheries        44
grapes         33
watermelons    45
peeches        56
dtype: int64

## Indexing and Slicing

In [11]:
s1

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
5     6.0
6    66.0
7    76.0
8    23.4
dtype: float64

In [12]:
s1[4]

np.float64(55.0)

In [13]:
s1[3:7]

3    44.0
4    55.0
5     6.0
6    66.0
dtype: float64

In [14]:
s2["bananas"]

np.int64(23)

In [15]:
s2["oranges":"watermelons"]   #In labels(string indices) the last index would be added but in number indices the last index would not be come in the output

oranges        12
bananas        23
mangoes        22
cheries        44
grapes         33
watermelons    45
dtype: int64

# Data Frame
  - 2 Dimensional Data
  - Data with more than one column

### YouTube Work

In [48]:
df=pd.DataFrame({"Name":["Khuzaima","Irshad","Arshad","Ashraf","Arsalan","Aun"],
                "Roll":[11,23,45,54,65,54],
               "Python":[76,98,75,69,43,19]})
df

       Name  Roll  Python
0  Khuzaima    11      76
1    Irshad    23      98
2    Arshad    45      75
3    Ashraf    54      69
4   Arsalan    65      43
5       Aun    54      19

## Data Loading

If we have the data file in another folder,So we can write the address of that file with the file name

In [96]:
emp1=pd.read_excel("D:\AI And Data Science\Pandas\employee.xlsx")

We write like this or if the warning comes we can change the backslesh into front slesch or we can write 'r' before the inverted commas ,
like this:
       DF=pd.read_excel(r"D:\AI And Data Science\Pandas\employee.xlsx")
So the file canbe readed easily.

In [97]:
emp1

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    1005     Manager          HR  45.0  120000.0
19      20    2123  Office Boy    Accounts  27.0   45000.0
20      21    6543     Officer  Production  29.0  100000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0
24      25    2156    Engineer  Production  45.0   89000.0
25      26    2123  Office Boy    Accounts  27.0   45000.0

In [98]:
emp1.shape

(26, 6)

In [99]:
emp1.head()

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
1       2    1107     Officer         IT  30.0   80000.0
2       3    1203     Officer         HR  28.0       NaN
3       4    1005     Manager         HR  45.0  120000.0
4       5    2123  Office Boy   Accounts  27.0   45000.0

In [100]:
emp1.tail()

    Serial  Emp_ID Designation  Department   Age    Salary
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0
24      25    2156    Engineer  Production  45.0   89000.0
25      26    2123  Office Boy    Accounts  27.0   45000.0

In [101]:
emp1.sample(3)

    Serial  Emp_ID Designation Department   Age   Salary
15      16    1222     Officer        NaN  25.0      NaN
19      20    2123  Office Boy   Accounts  27.0  45000.0
7        8    1001     Officer         IT  25.0  75000.0

In [102]:
emp1.columns

Index(['Serial', 'Emp_ID', 'Designation', 'Department', 'Age', 'Salary'], dtype='object')

In [103]:
emp1.index

RangeIndex(start=0, stop=26, step=1)

#### Working with columns

- select col
- Del col
- Update col
- Create new col from old cols
- merge cols
- Split cols

Selecting a Single Col

In [104]:
emp1['Designation']

0        Manager
1        Officer
2        Officer
3        Manager
4     Office Boy
5     Accountant
6     Accountant
7        Officer
8        Manager
9       Engineer
10       Officer
11    Accountant
12      Engineer
13       Officer
14       Officer
15       Officer
16      Engineer
17    Office Boy
18       Manager
19    Office Boy
20       Officer
21    Accountant
22      Engineer
23       Officer
24      Engineer
25    Office Boy
Name: Designation, dtype: object

In [105]:
emp1['Age']

0     50.0
1     30.0
2     28.0
3     45.0
4     27.0
5     34.0
6      NaN
7     25.0
8     23.0
9     45.0
10    29.0
11    49.0
12    45.0
13    25.0
14    31.0
15    25.0
16    45.0
17    27.0
18    45.0
19    27.0
20    29.0
21    49.0
22    45.0
23    25.0
24    45.0
25    27.0
Name: Age, dtype: float64

In [106]:
emp1.Age

0     50.0
1     30.0
2     28.0
3     45.0
4     27.0
5     34.0
6      NaN
7     25.0
8     23.0
9     45.0
10    29.0
11    49.0
12    45.0
13    25.0
14    31.0
15    25.0
16    45.0
17    27.0
18    45.0
19    27.0
20    29.0
21    49.0
22    45.0
23    25.0
24    45.0
25    27.0
Name: Age, dtype: float64

### Selecting a Multiple Column

In [107]:
emp1[["Emp_ID","Designation","Age","Salary"]] #We provide a list of columns to select more than one columns, And use two square brackets,First is of performing operation and second is of list

    Emp_ID Designation   Age    Salary
0     1101     Manager  50.0  200000.0
1     1107     Officer  30.0   80000.0
2     1203     Officer  28.0       NaN
3     1005     Manager  45.0  120000.0
4     2123  Office Boy  27.0   45000.0
5     2451  Accountant  34.0  100000.0
6     1111  Accountant   NaN  110000.0
7     1001     Officer  25.0   75000.0
8     1234     Manager  23.0       NaN
9     2156    Engineer  45.0   89000.0
10    6543     Officer  29.0  100000.0
11    3214  Accountant  49.0  123000.0
12    2156    Engineer  45.0   89000.0
13    1098     Officer  25.0  100000.0
14    2912     Officer  31.0   90000.0
15    1222     Officer  25.0       NaN
16    2156    Engineer  45.0   89000.0
17    2123  Office Boy  27.0   45000.0
18    1005     Manager  45.0  120000.0
19    2123  Office Boy  27.0   45000.0
20    6543     Officer  29.0  100000.0
21    3214  Accountant  49.0  123000.0
22    2156    Engineer  45.0   89000.0
23    1098     Officer  25.0  100000.0
24    2156    Engineer  45.0   89000.0
25    2123  Office Boy  27.0   45000.0

In [108]:
# Or we can filter out them without any manner
emp1[["Designation","Age","Salary","Emp_ID"]]

   Designation   Age    Salary  Emp_ID
0      Manager  50.0  200000.0    1101
1      Officer  30.0   80000.0    1107
2      Officer  28.0       NaN    1203
3      Manager  45.0  120000.0    1005
4   Office Boy  27.0   45000.0    2123
5   Accountant  34.0  100000.0    2451
6   Accountant   NaN  110000.0    1111
7      Officer  25.0   75000.0    1001
8      Manager  23.0       NaN    1234
9     Engineer  45.0   89000.0    2156
10     Officer  29.0  100000.0    6543
11  Accountant  49.0  123000.0    3214
12    Engineer  45.0   89000.0    2156
13     Officer  25.0  100000.0    1098
14     Officer  31.0   90000.0    2912
15     Officer  25.0       NaN    1222
16    Engineer  45.0   89000.0    2156
17  Office Boy  27.0   45000.0    2123
18     Manager  45.0  120000.0    1005
19  Office Boy  27.0   45000.0    2123
20     Officer  29.0  100000.0    6543
21  Accountant  49.0  123000.0    3214
22    Engineer  45.0   89000.0    2156
23     Officer  25.0  100000.0    1098
24    Engineer  45.0   89000.0    2156
25  Office Boy  27.0   45000.0    2123

In [109]:
emp1["tax%"]=15
emp1

    Serial  Emp_ID Designation  Department   Age    Salary  tax%
0        1    1101     Manager    Accounts  50.0  200000.0    15
1        2    1107     Officer          IT  30.0   80000.0    15
2        3    1203     Officer          HR  28.0       NaN    15
3        4    1005     Manager          HR  45.0  120000.0    15
4        5    2123  Office Boy    Accounts  27.0   45000.0    15
5        6    2451  Accountant         NaN  34.0  100000.0    15
6        7    1111  Accountant    Accounts   NaN  110000.0    15
7        8    1001     Officer          IT  25.0   75000.0    15
8        9    1234     Manager          IT  23.0       NaN    15
9       10    2156    Engineer  Production  45.0   89000.0    15
10      11    6543     Officer  Production  29.0  100000.0    15
11      12    3214  Accountant     Account  49.0  123000.0    15
12      13    2156    Engineer  Production  45.0   89000.0    15
13      14    1098     Officer          IT  25.0  100000.0    15
14      15    2912     Officer          IT  31.0   90000.0    15
15      16    1222     Officer         NaN  25.0       NaN    15
16      17    2156    Engineer  Production  45.0   89000.0    15
17      18    2123  Office Boy    Accounts  27.0   45000.0    15
18      19    1005     Manager          HR  45.0  120000.0    15
19      20    2123  Office Boy    Accounts  27.0   45000.0    15
20      21    6543     Officer  Production  29.0  100000.0    15
21      22    3214  Accountant     Account  49.0  123000.0    15
22      23    2156    Engineer  Production  45.0   89000.0    15
23      24    1098     Officer          IT  25.0  100000.0    15
24      25    2156    Engineer  Production  45.0   89000.0    15
25      26    2123  Office Boy    Accounts  27.0   45000.0    15

Outline Function :Its scope is Global

In [110]:
def decide_tax_percentage(sal):
    if sal>=200000:
        return 20
    if sal>=150000:
        return 15
    if sal>=100000:
        return 10
    if sal>=50000:
        return 5
    else:
        return 0

In [111]:
emp1["tax%"]=emp1.Salary.apply(decide_tax_percentage)

Inline Function:Scope is in the given column

In [112]:
emp1["tax%"]= emp1.Salary.apply(lambda x: 20 if x>=200000 else 15 if x>=150000 else 10 if x>=100000 else 5 if x>=50000 else 0) #There x refers the variable that stores each values like sal in outline function

In [113]:
def decide_tax_amt(sal):
    if sal>=200000:
        return sal*.20
    elif sal>=150000:
        return sal*.15
    elif sal>=100000:
        return sal*.10
    elif sal>=50000:
        return sal*.05
    else:
        return 0

In [114]:
emp1["Tax_Amount"] = emp1.Salary.apply(decide_tax_amt)

In [117]:
emp1["Tax_Amount"]=emp1.Salary.apply(lambda x: x*.20 if x>=200000 else x*.15 if x>=150000 else x*.10 if x>=100000 else x*.05 if x>=50000 else 0)

In [118]:
emp1

    Serial  Emp_ID Designation  Department   Age    Salary  tax%  Tax_Amount
0        1    1101     Manager    Accounts  50.0  200000.0    20     40000.0
1        2    1107     Officer          IT  30.0   80000.0     5      4000.0
2        3    1203     Officer          HR  28.0       NaN     0         0.0
3        4    1005     Manager          HR  45.0  120000.0    10     12000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0     0         0.0
5        6    2451  Accountant         NaN  34.0  100000.0    10     10000.0
6        7    1111  Accountant    Accounts   NaN  110000.0    10     11000.0
7        8    1001     Officer          IT  25.0   75000.0     5      3750.0
8        9    1234     Manager          IT  23.0       NaN     0         0.0
9       10    2156    Engineer  Production  45.0   89000.0     5      4450.0
10      11    6543     Officer  Production  29.0  100000.0    10     10000.0
11      12    3214  Accountant     Account  49.0  123000.0    10     12300.0
12      13    2156    Engineer  Production  45.0   89000.0     5      4450.0
13      14    1098     Officer          IT  25.0  100000.0    10     10000.0
14      15    2912     Officer          IT  31.0   90000.0     5      4500.0
15      16    1222     Officer         NaN  25.0       NaN     0         0.0
16      17    2156    Engineer  Production  45.0   89000.0     5      4450.0
17      18    2123  Office Boy    Accounts  27.0   45000.0     0         0.0
18      19    1005     Manager          HR  45.0  120000.0    10     12000.0
19      20    2123  Office Boy    Accounts  27.0   45000.0     0         0.0
20      21    6543     Officer  Production  29.0  100000.0    10     10000.0
21      22    3214  Accountant     Account  49.0  123000.0    10     12300.0
22      23    2156    Engineer  Production  45.0   89000.0     5      4450.0
23      24    1098     Officer          IT  25.0  100000.0    10     10000.0
24      25    2156    Engineer  Production  45.0   89000.0     5      4450.0
25      26    2123  Office Boy    Accounts  27.0   45000.0     0         0.0

In [119]:
emp1["Net"]=emp1.Salary - emp1.Tax_Amount

In [120]:
emp1

,Serial,Emp_ID,Designation,Department,Age,Salary,tax%,Tax_Amount,Net
0,1,1101,Manager,Accounts,50.0,200000.0,20,40000.0,160000.0
1,2,1107,Officer,IT,30.0,80000.0,5,4000.0,76000.0
2,3,1203,Officer,HR,28.0,NaN,0,0.0,NaN
3,4,1005,Manager,HR,45.0,120000.0,10,12000.0,108000.0
4,5,2123,Office Boy,Accounts,27.0,45000.0,0,0.0,45000.0
5,6,2451,Accountant,NaN,34.0,100000.0,10,10000.0,90000.0
6,7,1111,Accountant,Accounts,NaN,110000.0,10,11000.0,99000.0
7,8,1001,Officer,IT,25.0,75000.0,5,3750.0,71250.0
8,9,1234,Manager,IT,23.0,NaN,0,0.0,NaN
9,10,2156,Engineer,Production,45.0,89000.0,5,4450.0,84550.0
10,11,6543,Officer,Production,29.0,100000.0,10,10000.0,90000.0
11,12,3214,Accountant,Account,49.0,123000.0,10,12300.0,110700.0
12,13,2156,Engineer,Production,45.0,89000.0,5,4450.0,84550.0
13,14,1098,Officer,IT,25.0,100000.0,10,10000.0,90000.0
14,15,2912,Officer,IT,31.0,90000.0,5,4500.0,85500.0
15,16,1222,Officer,NaN,25.0,NaN,0,0.0,NaN
16,17,2156,Engineer,Production,45.0,89000.0,5,4450.0,84550.0
17,18,2123,Office Boy,Accounts,27.0,45000.0,0,0.0,45000.0
18,19,1005,Manager,HR,45.0,120000.0,10,12000.0,108000.0
19,20,2123,Office Boy,Accounts,27.0,45000.0,0,0.0,45000.0
20,21,6543,Officer,Production,29.0,100000.0,10,10000.0,90000.0
21,22,3214,Accountant,Account,49.0,123000.0,10,12300.0,110700.0
22,23,2156,Engineer,Production,45.0,89000.0,5,4450.0,84550.0
23,24,1098,Officer,IT,25.0,100000.0,10,10000.0,90000.0
24,25,2156,Engineer,Production,45.0,89000.0,5,4450.0,84550.0
25,26,2123,Office Boy,Accounts,27.0,45000.0,0,0.0,45000.0

### Class Work

In [16]:
result =     {"Roll":[12,32,43,54,54,75,32,56,67,34],
             "Name":["Khuzaima","Aman","Yasir","Tahir","Kamran","Taha","Talha","Saeed","Zubair","Irfan"],
             "Python":[23,34,35,54,76,98,23,56,78,89],
             "Pandas":[23,43,54,31,85,95,34,56,89,65],
             "Statistics":[23,24,57,78,96,54,90,87,56,34],
             "MachineLearning":[21,75,96,54,34,23,45,89,65,43],
             "DeepLearning":[21,85,65,34,12,87,89,76,56,43]} 
result

{'Roll': [12, 32, 43, 54, 54, 75, 32, 56, 67, 34],
 'Name': ['Khuzaima',
  'Aman',
  'Yasir',
  'Tahir',
  'Kamran',
  'Taha',
  'Talha',
  'Saeed',
  'Zubair',
  'Irfan'],
 'Python': [23, 34, 35, 54, 76, 98, 23, 56, 78, 89],
 'Pandas': [23, 43, 54, 31, 85, 95, 34, 56, 89, 65],
 'Statistics': [23, 24, 57, 78, 96, 54, 90, 87, 56, 34],
 'MachineLearning': [21, 75, 96, 54, 34, 23, 45, 89, 65, 43],
 'DeepLearning': [21, 85, 65, 34, 12, 87, 89, 76, 56, 43]}

In [17]:
result=pd.DataFrame(result)
result

   Roll      Name  Python  Pandas  Statistics  MachineLearning  DeepLearning
0    12  Khuzaima      23      23          23               21            21
1    32      Aman      34      43          24               75            85
2    43     Yasir      35      54          57               96            65
3    54     Tahir      54      31          78               54            34
4    54    Kamran      76      85          96               34            12
5    75      Taha      98      95          54               23            87
6    32     Talha      23      34          90               45            89
7    56     Saeed      56      56          87               89            76
8    67    Zubair      78      89          56               65            56
9    34     Irfan      89      65          34               43            43

## Working With Columns

- Adding more cloumns to dataframe
      - Passing hard coded values
      - generate data form data
- del columns from dataframe
- Acces single column (series)
- Acces multiple columns (2D)

In [18]:
result['Total']=result.Python + result.Pandas + result.Statistics + result.MachineLearning + result.DeepLearning
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total
0,12,Khuzaima,23,23,23,21,21,111
1,32,Aman,34,43,24,75,85,261
2,43,Yasir,35,54,57,96,65,307
3,54,Tahir,54,31,78,54,34,251
4,54,Kamran,76,85,96,34,12,303
5,75,Taha,98,95,54,23,87,357
6,32,Talha,23,34,90,45,89,281
7,56,Saeed,56,56,87,89,76,364
8,67,Zubair,78,89,56,65,56,344
9,34,Irfan,89,65,34,43,43,274

In [19]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total
0,12,Khuzaima,23,23,23,21,21,111
1,32,Aman,34,43,24,75,85,261
2,43,Yasir,35,54,57,96,65,307
3,54,Tahir,54,31,78,54,34,251
4,54,Kamran,76,85,96,34,12,303
5,75,Taha,98,95,54,23,87,357
6,32,Talha,23,34,90,45,89,281
7,56,Saeed,56,56,87,89,76,364
8,67,Zubair,78,89,56,65,56,344
9,34,Irfan,89,65,34,43,43,274

In [20]:
result["Percentage"]=result.Total/500*100
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage
0,12,Khuzaima,23,23,23,21,21,111,22.2
1,32,Aman,34,43,24,75,85,261,52.2
2,43,Yasir,35,54,57,96,65,307,61.4
3,54,Tahir,54,31,78,54,34,251,50.2
4,54,Kamran,76,85,96,34,12,303,60.6
5,75,Taha,98,95,54,23,87,357,71.4
6,32,Talha,23,34,90,45,89,281,56.2
7,56,Saeed,56,56,87,89,76,364,72.8
8,67,Zubair,78,89,56,65,56,344,68.8
9,34,Irfan,89,65,34,43,43,274,54.8

##### By Using List Comprehension

In [21]:
result["Grade"]= ["A+" if per>=70 else "A" if per>=60 else "B" if per>=50 else "C" if per>=40 else "D" if per>=30 else "E" if per>=20 else "F"  for per in result.Percentage]

In [22]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
0,12,Khuzaima,23,23,23,21,21,111,22.2,E
1,32,Aman,34,43,24,75,85,261,52.2,B
2,43,Yasir,35,54,57,96,65,307,61.4,A
3,54,Tahir,54,31,78,54,34,251,50.2,B
4,54,Kamran,76,85,96,34,12,303,60.6,A
5,75,Taha,98,95,54,23,87,357,71.4,A+
6,32,Talha,23,34,90,45,89,281,56.2,B
7,56,Saeed,56,56,87,89,76,364,72.8,A+
8,67,Zubair,78,89,56,65,56,344,68.8,A
9,34,Irfan,89,65,34,43,43,274,54.8,B

#### By Lamda Function
- They are Anonymous Function/Inline function

In [23]:
result["Grade1"]=result.Percentage.apply(lambda per:"A+" if per>=70 else "A" if per>=60 else "B" if per>=50 else "C" if per>=40 else "D" if per >=30 else "E" if per>=20 else "F")

In [24]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade,Grade1
0,12,Khuzaima,23,23,23,21,21,111,22.2,E,E
1,32,Aman,34,43,24,75,85,261,52.2,B,B
2,43,Yasir,35,54,57,96,65,307,61.4,A,A
3,54,Tahir,54,31,78,54,34,251,50.2,B,B
4,54,Kamran,76,85,96,34,12,303,60.6,A,A
5,75,Taha,98,95,54,23,87,357,71.4,A+,A+
6,32,Talha,23,34,90,45,89,281,56.2,B,B
7,56,Saeed,56,56,87,89,76,364,72.8,A+,A+
8,67,Zubair,78,89,56,65,56,344,68.8,A,A
9,34,Irfan,89,65,34,43,43,274,54.8,B,B

### Outline Function

In [25]:
def calculate_grade(per):
    if per>=70:
        return "A+"
    elif per>=60:
        return "A"
    elif per>=50:
        return "B"
    elif per>=40:
        return "C"
    elif per>=30:
        return "D"
    elif per>=20:
        return "E"
    else:
        return "F"

In [26]:
result["Grade2"]=result.Percentage.apply(calculate_grade)

In [27]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade,Grade1,Grade2
0,12,Khuzaima,23,23,23,21,21,111,22.2,E,E,E
1,32,Aman,34,43,24,75,85,261,52.2,B,B,B
2,43,Yasir,35,54,57,96,65,307,61.4,A,A,A
3,54,Tahir,54,31,78,54,34,251,50.2,B,B,B
4,54,Kamran,76,85,96,34,12,303,60.6,A,A,A
5,75,Taha,98,95,54,23,87,357,71.4,A+,A+,A+
6,32,Talha,23,34,90,45,89,281,56.2,B,B,B
7,56,Saeed,56,56,87,89,76,364,72.8,A+,A+,A+
8,67,Zubair,78,89,56,65,56,344,68.8,A,A,A
9,34,Irfan,89,65,34,43,43,274,54.8,B,B,B

In [28]:
del result["Grade1"]
del result["Grade2"]

In [29]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
0,12,Khuzaima,23,23,23,21,21,111,22.2,E
1,32,Aman,34,43,24,75,85,261,52.2,B
2,43,Yasir,35,54,57,96,65,307,61.4,A
3,54,Tahir,54,31,78,54,34,251,50.2,B
4,54,Kamran,76,85,96,34,12,303,60.6,A
5,75,Taha,98,95,54,23,87,357,71.4,A+
6,32,Talha,23,34,90,45,89,281,56.2,B
7,56,Saeed,56,56,87,89,76,364,72.8,A+
8,67,Zubair,78,89,56,65,56,344,68.8,A
9,34,Irfan,89,65,34,43,43,274,54.8,B

### Accesing Columns
   - Single Columns
   - Multiple Columns

In [30]:
result["Total"]

0    111
1    261
2    307
3    251
4    303
5    357
6    281
7    364
8    344
9    274
Name: Total, dtype: int64

In [31]:
result.Total #But for those who doesn't have gaped named key

0    111
1    261
2    307
3    251
4    303
5    357
6    281
7    364
8    344
9    274
Name: Total, dtype: int64

In [32]:
result[["Name","Grade"]] #For eccessing more than one key we sue double square brackets

       Name Grade
0  Khuzaima     E
1      Aman     B
2     Yasir     A
3     Tahir     B
4    Kamran     A
5      Taha    A+
6     Talha     B
7     Saeed    A+
8    Zubair     A
9     Irfan     B

In [33]:
result.Total.max()

364

In [34]:
result.Name.size

10

In [35]:
result.Total.mean()

np.float64(285.3)

#### Unique
- nunique
- unique

In [36]:
result.Grade.nunique()

4

In [37]:
result.Grade.unique()

array(['E', 'B', 'A', 'A+'], dtype=object)

In [38]:
result.Grade.value_counts()

Grade
B     4
A     3
A+    2
E     1
Name: count, dtype: int64

In [39]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
0,12,Khuzaima,23,23,23,21,21,111,22.2,E
1,32,Aman,34,43,24,75,85,261,52.2,B
2,43,Yasir,35,54,57,96,65,307,61.4,A
3,54,Tahir,54,31,78,54,34,251,50.2,B
4,54,Kamran,76,85,96,34,12,303,60.6,A
5,75,Taha,98,95,54,23,87,357,71.4,A+
6,32,Talha,23,34,90,45,89,281,56.2,B
7,56,Saeed,56,56,87,89,76,364,72.8,A+
8,67,Zubair,78,89,56,65,56,344,68.8,A
9,34,Irfan,89,65,34,43,43,274,54.8,B

### Accessing Row /Rows

result[Rows,Columns]
result[start_row:end_row:step , start_column:end_column]

In [40]:
result[4,"DeepLearning"]

KeyError: (4, 'DeepLearning')

In [ ]:
result[4,6]

In [ ]:
result.iloc[4,6]

In [ ]:
result.loc[4,"DeepLearning"]

In [ ]:
result.index

In [ ]:
result.columns

In [ ]:
result.loc[2:6,["Total","Percentage","Grade"]]   #from loc it can give all the values ,but with iloc it gives -1 .

In [ ]:
result.loc[::2,["Total","Percentage","Grade"]]

In [ ]:
result.loc[::2,::2]

In [ ]:
result.loc[[3,6,9] ,["Roll","Grade","Python"]]

In [ ]:
result.loc[3:5,"Pandas":"DeepLearning"]

## Query Filters

In [ ]:
result

In [ ]:
#Fetch all students having stats marks less than 80
result[result.Statistics<80]

In [ ]:
#For extracting those names having first letter with vowel
result[(result.Name.str[0]=="A") | (result.Name.str[0]=="E") | (result.Name.str[0]=="I") | (result.Name.str[0]=="O") | (result.Name.str[0]=="U")]

In [44]:
result.sort_values(by="Percentage",ascending=False,axis=0)

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
7,56,Saeed,56,56,87,89,76,364,72.8,A+
5,75,Taha,98,95,54,23,87,357,71.4,A+
8,67,Zubair,78,89,56,65,56,344,68.8,A
2,43,Yasir,35,54,57,96,65,307,61.4,A
4,54,Kamran,76,85,96,34,12,303,60.6,A
6,32,Talha,23,34,90,45,89,281,56.2,B
9,34,Irfan,89,65,34,43,43,274,54.8,B
1,32,Aman,34,43,24,75,85,261,52.2,B
3,54,Tahir,54,31,78,54,34,251,50.2,B
0,12,Khuzaima,23,23,23,21,21,111,22.2,E

In [45]:
#Students that have garde A and marks in Pandas greater than 80
result[(result.Grade=="A") & (result.Pandas>80)]

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
4,54,Kamran,76,85,96,34,12,303,60.6,A
8,67,Zubair,78,89,56,65,56,344,68.8,A

In [46]:
#Students that have greater marks in ML
result.MachineLearning.max()

96

In [47]:
result[result.MachineLearning==result.MachineLearning.max()]

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
2,43,Yasir,35,54,57,96,65,307,61.4,A

In [48]:
df=pd.read_csv("ai_student_impact_dataset.csv")

In [49]:
df.shape

(50000, 16)

In [51]:
df.head(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
7,100008,Arts,Junior,2.746,5.33,Copywriting/Drafting,Intermediate,3,False,18.45,2,Actively_Encouraged,1,2.965,85.09,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
9,100010,Business,Sophomore,3.046,19.99,Debugging/Troubleshooting,Intermediate,2,True,12.49,3,Strict_Ban,8,2.978,87.18,High

In [52]:
df.tail(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49990,149991,Business,Senior,2.970,2.63,Summarizing_Reading,Intermediate,2,False,24.95,1,Allowed_With_Citation,1,3.238,84.87,Medium
49991,149992,Humanities,Freshman,2.708,13.34,Copywriting/Drafting,Intermediate,2,False,11.65,4,Allowed_With_Citation,5,2.785,65.24,High
49992,149993,Business,Graduate,2.829,2.59,Debugging/Troubleshooting,Advanced,3,True,7.54,1,Allowed_With_Citation,4,3.176,84.04,Low
49993,149994,STEM,Sophomore,3.588,25.64,Debugging/Troubleshooting,Intermediate,3,True,4.62,5,Strict_Ban,10,3.841,58.44,High
49994,149995,Humanities,Senior,3.556,15.19,Summarizing_Reading,Advanced,4,True,1.00,3,Actively_Encouraged,5,3.788,74.76,High
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [53]:
df.sample(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
3516,103517,STEM,Freshman,3.226,2.47,Debugging/Troubleshooting,Advanced,3,False,22.22,3,Allowed_With_Citation,8,3.770,93.70,Medium
34916,134917,Arts,Junior,2.907,10.55,Summarizing_Reading,Beginner,3,True,13.25,5,Allowed_With_Citation,2,3.228,54.11,Medium
21922,121923,Humanities,Senior,3.454,25.08,Copywriting/Drafting,Intermediate,4,True,6.98,5,Actively_Encouraged,3,3.668,79.78,Medium
2603,102604,Humanities,Junior,2.557,10.21,Copywriting/Drafting,Advanced,5,False,8.42,5,Strict_Ban,7,2.507,80.99,Medium
47527,147528,Humanities,Graduate,2.518,10.77,Direct_Answer_Generation,Intermediate,1,False,12.40,6,Actively_Encouraged,5,2.628,68.44,High
34418,134419,Business,Graduate,2.460,4.12,Direct_Answer_Generation,Intermediate,2,False,9.80,1,Allowed_With_Citation,5,2.690,77.08,High
11398,111399,Humanities,Junior,3.430,3.08,Direct_Answer_Generation,Intermediate,3,False,14.87,4,Strict_Ban,6,3.780,74.68,Medium
30113,130114,STEM,Junior,3.340,33.24,Debugging/Troubleshooting,Advanced,3,False,5.44,7,Allowed_With_Citation,1,3.631,87.69,High
35903,135904,STEM,Senior,2.669,2.50,Copywriting/Drafting,Intermediate,3,False,13.68,2,Allowed_With_Citation,3,3.050,71.78,Low
38511,138512,Humanities,Sophomore,2.492,12.98,Ideation,Intermediate,2,False,8.54,3,Allowed_With_Citation,2,2.783,69.91,Medium

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB

In [55]:
df.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='object')

In [58]:
df.Major_Category.nunique()

5

In [61]:
df.Major_Category.value_counts()

Major_Category
STEM          15059
Business      12538
Humanities     9994
Medical        6476
Arts           5933
Name: count, dtype: int64

In [62]:
df.Year_of_Study.value_counts()

Year_of_Study
Junior       11045
Freshman     11031
Senior       10634
Sophomore     9860
Graduate      7430
Name: count, dtype: int64

In [67]:
df.Pre_Semester_GPA.mean()

np.float64(3.14610234)

In [71]:
#For finding out only those Major_Category columns whose values are STEM and takes their Pre_Semester_GPA and finds their mean
df[df.Major_Category=="STEM"]["Pre_Semester_GPA"].mean()

np.float64(3.14585184939239)

In [72]:
df[df.Major_Category=="Business"]["Pre_Semester_GPA"].mean()

np.float64(3.1417598500558297)

In [73]:
df[df.Major_Category=="Humanities"]["Pre_Semester_GPA"].mean()

np.float64(3.1478495097058237)

In [74]:
df[df.Major_Category=="Medical"]["Pre_Semester_GPA"].mean()

np.float64(3.151769302038295)

In [75]:
df[df.Major_Category=="Arts"]["Pre_Semester_GPA"].mean()

np.float64(3.1467862801280972)

In [79]:
emp=pd.read_excel("employee.xlsx",index_col="Serial")
emp

        Emp_ID Designation  Department   Age    Salary
Serial
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
11        6543     Officer  Production  29.0  100000.0
12        3214  Accountant     Account  49.0  123000.0
13        2156    Engineer  Production  45.0   89000.0
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   89000.0
18        2123  Office Boy    Accounts  27.0   45000.0
19        1005     Manager          HR  45.0  120000.0
20        2123  Office Boy    Accounts  27.0   45000.0
21        6543     Officer  Production  29.0  100000.0
22        3214  Accountant     Account  49.0  123000.0
23        2156    Engineer  Production  45.0   89000.0
24        1098     Officer          IT  25.0  100000.0
25        2156    Engineer  Production  45.0   89000.0
26        2123  Office Boy    Accounts  27.0   45000.0

In [80]:
#What is the average salary of managers
#what is the maxmum salary in IT Departement
#what is the average salary of accounts depart
#What is the most aged employee in the organization
#What the designation of the youngest employee

In [82]:
#What is the average salary of managers
emp[emp.Designation=="Manager"]["Salary"].mean()

np.float64(146666.66666666666)

In [83]:
#what is the maximum salary in IT Departement
emp[emp.Department=="IT"]["Salary"].max()

100000.0

In [84]:
#what is the average salary of accounts depart
emp[emp.Department=="Accounts"]["Salary"].mean()

np.float64(81666.66666666667)

In [88]:
#What is the most aged employee in the organization
emp[emp.Age==emp.Age.max()]

        Emp_ID Designation Department   Age    Salary
Serial
1         1101     Manager   Accounts  50.0  200000.0

In [89]:
#What the designation of the youngest employee
emp[emp.Age==emp.Age.min()]["Designation"]

Serial
9    Manager
Name: Designation, dtype: object